######################################################################
# Automatically generated by qmake (2.01a) ?? 8? 26 18:32:46 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += calendar.h draglabel.h editreminder.h setdialog.h
SOURCES += calendar.cpp draglabel.cpp editreminder.cpp main.cpp setdialog.cpp
