######################################################################
# Automatically generated by qmake (2.01a) ?? 8? 26 11:13:47 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += calendar.h draglabel.h setdialog.h
SOURCES += calendar.cpp draglabel.cpp main.cpp setdialog.cpp
